/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import proyectobases.Conexion;
/**
 *
 * @author ramir
 */
public class Cliente extends javax.swing.JPanel {
    Conexion con;
    /**
     * Creates new form Cliente
     * @param con
     */
    public Cliente(Conexion con) {
        initComponents();
        this.con=con;
        if ("Cliente".equals(con.getRol())){   
           GetInfo();
        }else if("Empleado".equals(con.getRol())||"Administrador".equals(con.getRol())){
        panelCliente.setVisible(false);
        }
    }
    public void GetInfo(){
    Connection conexion=con.getConexion();
    PreparedStatement ps = null;
    ResultSet rs = null;
    try {
        ps = conexion.prepareStatement("SELECT * from cliente join persona on cliente.Per_ID=persona.Per_ID where persona.Per_ID = ?;");
        ps.setInt(1, con.getId());
        rs = ps.executeQuery();
        if (rs.next()){
            
            lblCompras.setText("Compras : "+rs.getInt(2));
            lblDireccion.setText("Direccion : "+ rs.getString(7));
            lblIdentificacion.setText("Identificacion : "+ rs.getInt(3));
            lblNombre.setText("Nombre : "+ rs.getString(4));
            lblnumero.setText("Numero : "+rs.getLong(6));
            lblAppellido.setText("Apellido : "+ rs.getString(5));
            
        }
      } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al ejecutar la consulta: " + ex.getMessage());
            }
    
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblAppellido = new javax.swing.JLabel();
        lblCompras = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        btnDireccion = new javax.swing.JButton();
        btnNumero = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Cliente");

        panelCliente.setBackground(new java.awt.Color(204, 255, 204));
        panelCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 102, 0));
        lblNombre.setText("Nombre");
        panelCliente.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 537, -1));

        lblAppellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAppellido.setForeground(new java.awt.Color(0, 102, 0));
        lblAppellido.setText("Apellido");
        panelCliente.add(lblAppellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        lblCompras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCompras.setForeground(new java.awt.Color(0, 102, 0));
        lblCompras.setText("Compras");
        panelCliente.add(lblCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        lblIdentificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdentificacion.setForeground(new java.awt.Color(0, 102, 0));
        lblIdentificacion.setText("Identificacion");
        panelCliente.add(lblIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        lblnumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnumero.setForeground(new java.awt.Color(0, 102, 0));
        lblnumero.setText("Numero de telefono");
        panelCliente.add(lblnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(0, 102, 0));
        lblDireccion.setText("direccion");
        panelCliente.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        btnDireccion.setText("Actualizar");
        btnDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireccionActionPerformed(evt);
            }
        });
        panelCliente.add(btnDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        btnNumero.setText("Actualizar");
        btnNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroActionPerformed(evt);
            }
        });
        panelCliente.add(btnNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        btnrefresh.setText("Refrescar");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        panelCliente.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 163, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel1)
                .addContainerGap(389, Short.MAX_VALUE))
            .addComponent(panelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(panelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireccionActionPerformed
    actDire p = new actDire(con);  
    p.setVisible(true);
        System.out.println("si");// TODO add your handling code here:
    }//GEN-LAST:event_btnDireccionActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
GetInfo();        // TODO add your handling code here:
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroActionPerformed
acttel p = new acttel(con);
p.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnNumeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDireccion;
    private javax.swing.JButton btnNumero;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAppellido;
    private javax.swing.JLabel lblCompras;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JPanel panelCliente;
    // End of variables declaration//GEN-END:variables
}
